In [3]:
import numpy as np

In [4]:
my_array = np.random.randint(1, 101, size=(10, 3))

In [5]:
print(my_array)

[[43 26 75]
 [93 34 47]
 [56 99 15]
 [47 78  9]
 [27 11 54]
 [84 83  1]
 [80 74 65]
 [24 36 96]
 [48  3 15]
 [56 72 63]]
